// 商品カタログの原本。ここを編集して `node scripts/generate-seed.mjs` を実行すると
// data/products.json が再生成される。
//
// base    : 現地の定価（韓国ブランドは KRW、米国ブランドは USD）
// shops   : その商品を取り扱うショップID（lib/shops.ts の SHOPS と対応）
// popularity / trendScore : ランキングとトレンドバッジの並び順（0-100）
//
// ※ url は生成側でプレースホルダを組み立てている。実運用では各ショップの
//    商品URL／アフィリエイトリンクに差し替えること。

export const PRODUCTS = [
  {
    id: 'cosrx-snail-96-essence',
    name: 'COSRX アドバンスド スネイル 96 ムチン パワー エッセンス',
    nameOriginal: '코스알엑스 어드밴스드 스네일 96 뮤신 파워 에센스',
    brand: 'COSRX',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['乾燥', '毛穴', 'ゆらぎ肌', '定番', 'ムチン'],
    description:
      'カタツムリ分泌液を96%配合した、韓国スキンケアの入門定番エッセンス。とろみのあるテクスチャーで、乾燥した肌をひと晩で立て直したいときに。',
    highlights: ['スネイルセクリートフィルトレート96%', '無香料・弱酸性', '10年以上売れ続けるロングセラー'],
    popularity: 96,
    trendScore: 12,
    addedAt: '2026-01-12',
    base: { amount: 22000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'yesstyle', 'qoo10', 'amazon-jp', 'iherb'],
  },
  {
    id: 'anua-heartleaf-77-toner',
    name: 'Anua ドクダミ 77% スージングトナー',
    nameOriginal: '아누아 어성초 77 수딩 토너',
    brand: 'Anua',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['赤み', 'ニキビ', '鎮静', 'ドクダミ', 'バズり'],
    description:
      'ドクダミエキスを77%配合した鎮静トナー。TikTok経由で日本にも一気に広がり、韓国コスメの「鎮静ブーム」を決定づけた一本です。',
    highlights: ['ドクダミ抽出物77%', 'ふきとり・コットンパックの両対応', '敏感肌テスト済み'],
    popularity: 98,
    trendScore: 34,
    addedAt: '2026-02-03',
    base: { amount: 26000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'coupang-global', 'yesstyle', 'qoo10', 'rakuten'],
  },
  {
    id: 'anua-peach-70-niacin-serum',
    name: 'Anua ピーチ 70 ナイアシン セラム',
    nameOriginal: '아누아 피치 70 나이아신 세럼',
    brand: 'Anua',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['くすみ', 'トーンアップ', 'ナイアシンアミド', '毛穴'],
    description:
      'ピーチエキスとナイアシンアミドで、くすみと毛穴の目立ちにアプローチするセラム。ドクダミトナーと同ラインで揃える人が増えています。',
    highlights: ['ナイアシンアミド配合', 'べたつかない軽い使用感', '朝晩どちらでも使える'],
    popularity: 84,
    trendScore: 41,
    addedAt: '2026-03-18',
    base: { amount: 24000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'yesstyle', 'stylevana', 'qoo10'],
  },
  {
    id: 'boj-relief-sun-rice-probiotics',
    name: 'Beauty of Joseon リリーフサン ライス＋プロバイオティクス SPF50+',
    nameOriginal: '조선미녀 릴리프 선 라이스 프로바이오틱스',
    brand: 'Beauty of Joseon',
    brandCountry: 'KR',
    category: 'suncare',
    tags: ['日焼け止め', '白浮きしない', '乾燥', 'デイリー', 'バズり'],
    description:
      '米ぬかエキス配合の韓国製サンスクリーン。白浮きせず化粧下地としても使える軽さで、海外レビュアーの評価から日本に逆輸入されたヒット作。',
    highlights: ['SPF50+ PA++++', 'ミルクのような軽いテクスチャー', 'メイク前に使える'],
    popularity: 95,
    trendScore: 28,
    addedAt: '2026-01-25',
    base: { amount: 18000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'yesstyle', 'stylevana', 'amazon-jp', 'qoo10'],
  },
  {
    id: 'medicube-zero-pore-pad-2',
    name: 'medicube ゼロ毛穴パッド 2.0',
    nameOriginal: '메디큐브 제로 모공 패드 2.0',
    brand: 'medicube',
    brandCountry: 'KR',
    category: 'mask-sheet',
    tags: ['毛穴', '角質', '拭き取り', 'BHA', '皮脂'],
    description:
      '拭き取るだけで角質と皮脂をオフする毛穴ケアパッド。1枚あたりの単価がショップで大きく変わるため、総額比較の効果が大きい商品です。',
    highlights: ['70枚入り', 'AHA・BHA・PHA配合', '凹凸のあるエンボス面で拭き取り'],
    popularity: 91,
    trendScore: 22,
    addedAt: '2026-02-14',
    base: { amount: 32000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'coupang-global', 'qoo10', 'rakuten'],
  },
  {
    id: 'torriden-dive-in-serum',
    name: 'Torriden ダイブイン 低分子ヒアルロン酸セラム',
    nameOriginal: '토리든 다이브인 저분자 히알루론산 세럼',
    brand: 'Torriden',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['乾燥', '保湿', 'ヒアルロン酸', '敏感肌', '定番'],
    description:
      '5種の低分子ヒアルロン酸を配合した水のようなセラム。重ね付けしてもベタつかず、season問わず使える「とりあえずの1本」として定着しました。',
    highlights: ['低分子ヒアルロン酸5種', 'ヴィーガン認証', '無香料'],
    popularity: 93,
    trendScore: 15,
    addedAt: '2026-01-08',
    base: { amount: 22000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'naver-smartstore', 'yesstyle', 'qoo10', 'amazon-jp'],
  },
  {
    id: 'skin1004-centella-ampoule',
    name: 'SKIN1004 マダガスカル センテラ アンプル',
    nameOriginal: '스킨천사 마다가스카르 센텔라 암풀',
    brand: 'SKIN1004',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['鎮静', '赤み', 'ツボクサ', '敏感肌'],
    description:
      'マダガスカル産ツボクサエキスを100%使用したアンプル。ゆらいだ日のレスキューとして、化粧水の後に重ねる使い方が定番です。',
    highlights: ['ツボクサ抽出物100%', '成分表示が1つだけのシンプル処方', '低刺激テスト済み'],
    popularity: 88,
    trendScore: 18,
    addedAt: '2026-02-20',
    base: { amount: 25000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'yesstyle', 'stylevana', 'qoo10'],
  },
  {
    id: 'roundlab-dokdo-toner',
    name: 'Round Lab 1025 独島（ドクト）トナー',
    nameOriginal: '라운드랩 1025 독도 토너',
    brand: 'Round Lab',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['角質', '保湿', 'ミネラル', '敏感肌', '定番'],
    description:
      '独島の海洋深層水をベースにした、角質ケアと保湿を両立するトナー。刺激が少なく、大容量でコットンパックにも使いやすい一本。',
    highlights: ['海洋深層水配合', '低刺激のマイルドな角質ケア', '200mLの大容量'],
    popularity: 90,
    trendScore: 11,
    addedAt: '2026-01-30',
    base: { amount: 24000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'coupang-global', 'yesstyle', 'amazon-jp'],
  },
  {
    id: 'numbuzin-no3-collagen-serum',
    name: 'numbuzin 3番 ぷるぷるコラーゲン セラム',
    nameOriginal: '넘버즈인 3번 잘 익은 콜라겐 세럼',
    brand: 'numbuzin',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['ハリ', 'ツヤ', 'コラーゲン', 'エイジングケア'],
    description:
      '番号でラインを選ぶユニークなブランドの看板商品。コラーゲンとペプチドでハリとツヤを狙う、しっとり系のセラムです。',
    highlights: ['加水分解コラーゲン配合', 'とろみのあるテクスチャー', 'メイク前のツヤ出しにも'],
    popularity: 86,
    trendScore: 26,
    addedAt: '2026-03-02',
    base: { amount: 27000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'naver-smartstore', 'qoo10', 'rakuten'],
  },
  {
    id: 'vt-reedle-shot-100',
    name: 'VT リードルショット 100',
    nameOriginal: '브이티 리들샷 100',
    brand: 'VT Cosmetics',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['ハリ', '毛穴', 'ザラつき', 'バズり', 'エイジングケア'],
    description:
      '海綿由来のスピキュール（微細な針状成分）で肌に刺激を与える、話題の「針美容液」。使用直後のチクチク感が特徴で、SNSでの検証動画が拡散しました。',
    highlights: ['スピキュール配合', '数字が大きいほど高濃度', '週2〜3回のスペシャルケア向け'],
    popularity: 89,
    trendScore: 52,
    addedAt: '2026-04-06',
    base: { amount: 39000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'coupang-global', 'qoo10', 'rakuten', 'amazon-jp'],
  },
  {
    id: 'mixsoon-bean-essence',
    name: 'mixsoon ビーン エッセンス',
    nameOriginal: '믹순 빈 에센스',
    brand: 'mixsoon',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['角質', '発酵', 'シンプル処方', '敏感肌'],
    description:
      '発酵大豆エキスを主成分にした、成分数を絞ったエッセンス。角質をやわらげてごわつきを整える、いわゆる「ミニマル系」の代表格です。',
    highlights: ['発酵大豆エキス', '成分数を極力削ったシンプル処方', 'ヴィーガン'],
    popularity: 79,
    trendScore: 24,
    addedAt: '2026-02-27',
    base: { amount: 24000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'yesstyle', 'stylevana', 'qoo10'],
  },
  {
    id: 'dalba-white-truffle-serum',
    name: "d'Alba ホワイトトリュフ ファースト スプレー セラム",
    nameOriginal: '달바 화이트 트러플 퍼스트 스프레이 세럼',
    brand: "d'Alba",
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['ツヤ', '保湿', 'ミスト', 'ギフト', '免税店人気'],
    description:
      'スプレーで顔全体に広げるオイルインセラム。イタリア産白トリュフエキス配合で、韓国の免税店・空港で最も売れているミストのひとつです。',
    highlights: ['スプレータイプのオイルセラム', 'メイクの上からも使える', 'ギフト需要が高い'],
    popularity: 82,
    trendScore: 14,
    addedAt: '2026-01-19',
    base: { amount: 38000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'naver-smartstore', 'qoo10', 'rakuten'],
  },
  {
    id: 'tirtir-mask-fit-red-cushion',
    name: 'TIRTIR マスクフィット レッド クッション',
    nameOriginal: '티르티르 마스크 핏 레드 쿠션',
    brand: 'TIRTIR',
    brandCountry: 'KR',
    category: 'makeup',
    tags: ['クッションファンデ', 'カバー力', '色展開豊富', 'バズり'],
    description:
      '色番の少なさを指摘する海外レビューを受けて30色に拡張し、世界的にヒットしたクッションファンデ。高カバーでマスクにも付きにくい設計です。',
    highlights: ['SPF40 PA++', '30色の豊富なシェード', '崩れにくい高密着処方'],
    popularity: 94,
    trendScore: 38,
    addedAt: '2026-02-08',
    base: { amount: 29000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'coupang-global', 'qoo10', 'amazon-jp', 'rakuten'],
  },
  {
    id: 'clio-kill-cover-fixer-cushion',
    name: 'CLIO キルカバー ファンウェア クッション オールニュー',
    nameOriginal: '클리오 킬커버 매쉬글로우 쿠션',
    brand: 'CLIO',
    brandCountry: 'KR',
    category: 'makeup',
    tags: ['クッションファンデ', 'カバー力', 'ツヤ肌', '定番'],
    description:
      '韓国のドラッグストアで長く売れ続けているクッション。薄膜なのにカバーするバランスの良さで、初めての韓国ベースメイクに選ばれています。',
    highlights: ['詰め替え用リフィル付き', 'セミマットの仕上がり', 'SPF50+ PA+++'],
    popularity: 87,
    trendScore: 9,
    addedAt: '2026-01-15',
    base: { amount: 33000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'naver-smartstore', 'qoo10', 'rakuten'],
  },
  {
    id: 'romand-juicy-lasting-tint',
    name: 'rom&nd ジューシー ラスティング ティント',
    nameOriginal: '롬앤 쥬시 래스팅 틴트',
    brand: 'rom&nd',
    brandCountry: 'KR',
    category: 'makeup',
    tags: ['ティント', '落ちにくい', 'ツヤ', '定番', 'プチプラ'],
    description:
      '果実のようなツヤと落ちにくさで、日本でも定番化した韓国ティント。色番が非常に多く、限定色は現地でしか手に入らないことも。',
    highlights: ['みずみずしいツヤ感', '色持ちのよいティント処方', '限定色は韓国先行が多い'],
    popularity: 92,
    trendScore: 16,
    addedAt: '2026-01-05',
    base: { amount: 12000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'coupang-global', 'yesstyle', 'qoo10', 'amazon-jp'],
  },
  {
    id: 'peripera-ink-mood-glowy-tint',
    name: 'peripera インクムード グロウィ ティント',
    nameOriginal: '페리페라 잉크 무드 글로이 틴트',
    brand: 'peripera',
    brandCountry: 'KR',
    category: 'makeup',
    tags: ['ティント', 'ツヤ', 'プチプラ', '韓国限定色'],
    description:
      '軽いつけ心地とみずみずしいツヤが特徴のプチプラティント。単価が安いぶん、送料込みの総額で買う場所が大きく変わります。',
    highlights: ['1,000円台の価格帯', 'ぷるんとしたツヤ仕上げ', 'まとめ買い向き'],
    popularity: 81,
    trendScore: 19,
    addedAt: '2026-02-11',
    base: { amount: 11000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'yesstyle', 'stylevana', 'qoo10'],
  },
  {
    id: 'amuse-jel-fit-tint',
    name: 'AMUSE ジェルフィット ティント',
    nameOriginal: '어뮤즈 젤 핏 틴트',
    brand: 'AMUSE',
    brandCountry: 'KR',
    category: 'makeup',
    tags: ['ティント', 'ヴィーガン', 'ムード系', '韓国先行'],
    description:
      'ヴィーガン処方のクリーンビューティーブランド。落ち着いたムードカラーが揃い、日本未展開の色が多いのが輸入で選ばれる理由です。',
    highlights: ['ヴィーガン認証', 'ジェル質感のなめらかな発色', 'パッケージのデザイン性が高い'],
    popularity: 76,
    trendScore: 31,
    addedAt: '2026-03-22',
    base: { amount: 18000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'naver-smartstore', 'yesstyle', 'qoo10'],
  },
  {
    id: 'goodal-green-tangerine-pad',
    name: 'goodal 青みかん ビタC 濃縮 トナーパッド',
    nameOriginal: '구달 청귤 비타C 잡티케어 패드',
    brand: 'goodal',
    brandCountry: 'KR',
    category: 'mask-sheet',
    tags: ['くすみ', 'ビタミンC', 'トナーパッド', '済州島'],
    description:
      '済州島産の青みかんとビタミンC誘導体を配合したトナーパッド。朝のふき取りでトーンを整える使い方が人気です。',
    highlights: ['ビタミンC誘導体配合', '70枚入り', '朝のふき取りケアに'],
    popularity: 83,
    trendScore: 20,
    addedAt: '2026-02-24',
    base: { amount: 23000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'coupang-global', 'yesstyle', 'qoo10'],
  },
  {
    id: 'abib-heartleaf-spot-pad',
    name: 'Abib ドクダミ カーミング スポットパッド',
    nameOriginal: '아비브 어성초 카밍 패드',
    brand: 'Abib',
    brandCountry: 'KR',
    category: 'mask-sheet',
    tags: ['鎮静', 'ニキビ', 'ドクダミ', 'トナーパッド'],
    description:
      'ドクダミエキスを含ませた鎮静パッド。気になる部分に貼って置く「スポットパック」としても使える厚みが特徴です。',
    highlights: ['ドクダミ抽出物配合', '貼って置けるしっかりした厚み', '80枚入り'],
    popularity: 80,
    trendScore: 23,
    addedAt: '2026-03-09',
    base: { amount: 24000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'naver-smartstore', 'stylevana', 'qoo10'],
  },
  {
    id: 'mediheal-nmf-mask-10',
    name: 'MEDIHEAL N.M.F アクアリング アンプルマスク（10枚）',
    nameOriginal: '메디힐 N.M.F 아쿠아링 앰플 마스크',
    brand: 'MEDIHEAL',
    brandCountry: 'KR',
    category: 'mask-sheet',
    tags: ['シートマスク', '保湿', 'まとめ買い', '定番'],
    description:
      '韓国シートマスクの代名詞。10枚入りの箱買いが基本で、枚数と送料をあわせた「1枚あたりの総額」で比べるのがおすすめです。',
    highlights: ['1枚あたりの単価が安い', '密着するシート', 'まとめ買いで単価がさらに下がる'],
    popularity: 85,
    trendScore: 7,
    addedAt: '2026-01-10',
    base: { amount: 18000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'coupang-global', 'yesstyle', 'qoo10', 'amazon-jp'],
  },
  {
    id: 'isntree-hyaluronic-aqua-ampoule',
    name: 'Isntree ヒアルロニック アクア アンプル',
    nameOriginal: '이즈앤트리 히알루론산 아쿠아 앰플',
    brand: "Isntree",
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['保湿', 'ヒアルロン酸', '敏感肌', 'コスパ'],
    description:
      '8種のヒアルロン酸をブレンドした高保湿アンプル。大容量でコストパフォーマンスが高く、ボディにも使う人がいます。',
    highlights: ['ヒアルロン酸8種配合', '無香料・無着色', '大容量100mL'],
    popularity: 74,
    trendScore: 10,
    addedAt: '2026-02-01',
    base: { amount: 26000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'yesstyle', 'stylevana', 'qoo10'],
  },
  {
    id: 'axis-y-dark-spot-serum',
    name: 'Axis-Y ダークスポット コレクティング グロウ セラム',
    nameOriginal: '엑시스와이 다크스팟 코렉팅 글로우 세럼',
    brand: 'Axis-Y',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['くすみ', 'ニキビ跡', 'ナイアシンアミド', '海外人気'],
    description:
      'ナイアシンアミドとパパイヤ抽出物で、ニキビ跡やくすみにアプローチするセラム。韓国国内より海外での評価が先に高まった一本です。',
    highlights: ['ナイアシンアミド5%', 'ヴィーガン処方', '海外レビュー発の人気'],
    popularity: 72,
    trendScore: 17,
    addedAt: '2026-03-14',
    base: { amount: 25000, currency: 'KRW' },
    shops: ['yesstyle', 'stylevana', 'iherb', 'qoo10'],
  },
  {
    id: 'laneige-water-sleeping-mask',
    name: 'LANEIGE ウォータースリーピングマスク EX',
    nameOriginal: '라네즈 워터 슬리핑 마스크 EX',
    brand: 'LANEIGE',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['夜用パック', '保湿', '定番', 'デパコス'],
    description:
      '寝ている間に使う塗るパックの定番。米国のSephoraでも定番棚に並び、韓国コスメが海外で売れる流れを作った代表的な商品です。',
    highlights: ['塗って寝るだけのナイトパック', 'みずみずしいジェル質感', '米国でも定番の1つ'],
    popularity: 88,
    trendScore: 6,
    addedAt: '2026-01-03',
    base: { amount: 33000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'sephora-us', 'qoo10', 'amazon-jp', 'rakuten'],
  },
  {
    id: 'innisfree-black-tea-ampoule',
    name: 'innisfree ブラックティー ユース エンハンシング アンプル',
    nameOriginal: '이니스프리 블랙티 유스 인핸싱 앰플',
    brand: 'innisfree',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['エイジングケア', 'ハリ', '抗酸化', '済州島'],
    description:
      '済州島産の発酵紅茶エキスを使ったエイジングケアアンプル。とろみがあり、乾燥する季節の夜のケアに向いています。',
    highlights: ['発酵紅茶エキス配合', '抗酸化ケア', 'しっとりしたテクスチャー'],
    popularity: 70,
    trendScore: 8,
    addedAt: '2026-02-17',
    base: { amount: 42000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'naver-smartstore', 'qoo10', 'rakuten'],
  },
  {
    id: 'drg-red-blemish-cream',
    name: 'Dr.G レッドブレミッシュ クリア スージング クリーム',
    nameOriginal: '닥터지 레드 블레미쉬 클리어 수딩 크림',
    brand: 'Dr.G',
    brandCountry: 'KR',
    category: 'skincare',
    tags: ['赤み', '鎮静', '敏感肌', 'ツボクサ', '定番'],
    description:
      '韓国のドラッグストアで長年上位を占める鎮静クリーム。赤みが出やすい肌のデイリーケアとして、季節の変わり目に選ばれています。',
    highlights: ['ツボクサ由来成分配合', '軽いジェルクリーム', '敏感肌テスト済み'],
    popularity: 84,
    trendScore: 5,
    addedAt: '2026-01-22',
    base: { amount: 32000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'coupang-global', 'qoo10', 'amazon-jp'],
  },
  {
    id: 'miseenscene-perfect-serum',
    name: 'Mise en Scène パーフェクト セラム オリジナル',
    nameOriginal: '미쟝센 퍼펙트 세럼 오리지널',
    brand: 'Mise en Scène',
    brandCountry: 'KR',
    category: 'haircare',
    tags: ['ヘアオイル', 'ダメージ補修', '定番', 'プチプラ'],
    description:
      '韓国のヘアオイルといえばこれ、という定番。液体で重いため国際送料が効きやすく、日本国内在庫との総額差が出やすい商品です。',
    highlights: ['7種のオイル配合', 'ドライヤー前の熱ダメージ対策に', '香りのバリエーションが豊富'],
    popularity: 78,
    trendScore: 4,
    addedAt: '2026-01-17',
    base: { amount: 15000, currency: 'KRW' },
    shops: ['coupang-global', 'yesstyle', 'qoo10', 'amazon-jp'],
  },
  {
    id: 'aromatica-rosemary-scalp-scrub',
    name: 'AROMATICA ローズマリー スカルプ スクラブ',
    nameOriginal: '아로마티카 로즈마리 스칼프 스크럽',
    brand: 'AROMATICA',
    brandCountry: 'KR',
    category: 'haircare',
    tags: ['頭皮ケア', 'スクラブ', 'ヴィーガン', '海外人気'],
    description:
      '塩とローズマリーで頭皮の毛穴をすっきりさせるスクラブ。頭皮ケア（スカルプケア）ブームの火付け役として海外で先に売れた商品です。',
    highlights: ['天然塩ベースのスクラブ', 'ヴィーガン・EWGグリーン等級', '週1〜2回のスペシャルケア'],
    popularity: 68,
    trendScore: 29,
    addedAt: '2026-03-27',
    base: { amount: 28000, currency: 'KRW' },
    shops: ['oliveyoung-global', 'iherb', 'yesstyle', 'qoo10'],
  },
  {
    id: 'tamburins-perfume-hand-cream',
    name: 'TAMBURINS パフューム ハンドクリーム',
    nameOriginal: '탬버린즈 퍼퓸 핸드 크림',
    brand: 'TAMBURINS',
    brandCountry: 'KR',
    category: 'bodycare',
    tags: ['ハンドクリーム', '香り', 'ギフト', 'デザイン', '韓国限定'],
    description:
      'オブジェのようなパッケージで人気の韓国発ブランド。日本には店舗が限られ、限定の香りは現地でしか買えないためギフト目的の輸入が多い商品です。',
    highlights: ['香水のような香り立ち', 'ギフトに映えるパッケージ', '日本未発売の香りあり'],
    popularity: 77,
    trendScore: 36,
    addedAt: '2026-04-02',
    base: { amount: 26000, currency: 'KRW' },
    shops: ['naver-smartstore', 'coupang-global', 'qoo10', 'rakuten'],
  },
  {
    id: 'nonfiction-gentle-night-edp',
    name: 'Nonfiction ジェントル ナイト オードパルファム',
    nameOriginal: '논픽션 젠틀 나이트 오 드 퍼퓸',
    brand: 'Nonfiction',
    brandCountry: 'KR',
    category: 'fragrance',
    tags: ['香水', 'ニッチフレグランス', 'ユニセックス', '韓国限定'],
    description:
      'ソウル発のニッチフレグランス。落ち着いたムスク調で、K-POPアーティストの愛用から人気に火がつきました。',
    highlights: ['ユニセックスのムスク調', '日本での取扱いが少ない', '同じ香りのボディラインあり'],
    popularity: 66,
    trendScore: 44,
    addedAt: '2026-04-15',
    base: { amount: 130000, currency: 'KRW' },
    shops: ['naver-smartstore', 'coupang-global', 'qoo10'],
  },
  {
    id: 'medicube-age-r-booster-pro',
    name: 'medicube AGE-R ブースター プロ',
    nameOriginal: '메디큐브 에이지알 부스터 프로',
    brand: 'medicube',
    brandCountry: 'KR',
    category: 'tools',
    tags: ['美顔器', 'EMS', 'エイジングケア', '高単価'],
    description:
      '韓国のホームケア美顔器ブーム を代表する多機能デバイス。単価が高く、課税ラインを確実に超えるため総額のシミュレーションが特に重要です。',
    highlights: ['EMS・microカレントなど多機能', '韓国は220V。日本での使用は電圧確認が必須', '課税対象になりやすい価格帯'],
    popularity: 71,
    trendScore: 33,
    addedAt: '2026-03-05',
    base: { amount: 289000, currency: 'KRW' },
    shops: ['coupang-global', 'naver-smartstore', 'qoo10', 'rakuten'],
  },
  {
    id: 'the-ordinary-niacinamide',
    name: 'The Ordinary ナイアシンアミド 10% + 亜鉛 1%',
    nameOriginal: 'The Ordinary Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    brandCountry: 'US',
    category: 'skincare',
    tags: ['皮脂', '毛穴', 'ナイアシンアミド', 'コスパ', '定番'],
    description:
      '成分名をそのまま商品名にする合理主義で世界を変えたブランド。皮脂と毛穴のケアに使われる、1,000円前後の定番セラムです。',
    highlights: ['ナイアシンアミド10%', '1,000円前後の低価格', '他の美容液と重ねやすい'],
    popularity: 89,
    trendScore: 6,
    addedAt: '2026-01-06',
    base: { amount: 6.5, currency: 'USD' },
    shops: ['iherb', 'sephora-us', 'qoo10', 'amazon-jp'],
  },
  {
    id: 'cerave-moisturizing-cream',
    name: 'CeraVe モイスチャライジング クリーム 453g',
    nameOriginal: 'CeraVe Moisturizing Cream',
    brand: 'CeraVe',
    brandCountry: 'US',
    category: 'bodycare',
    tags: ['セラミド', '乾燥', '大容量', '皮膚科医推奨', '定番'],
    description:
      '3種のセラミドを配合した大容量保湿クリーム。顔にも体にも使え、米国の皮膚科医が勧める定番として日本でも支持を広げています。',
    highlights: ['セラミド3種＋ヒアルロン酸', '453gの大容量', '無香料・ノンコメドジェニック'],
    popularity: 87,
    trendScore: 13,
    addedAt: '2026-01-28',
    base: { amount: 18, currency: 'USD' },
    shops: ['iherb', 'amazon-jp', 'qoo10', 'rakuten'],
  },
  {
    id: 'glow-recipe-watermelon-toner',
    name: 'Glow Recipe ウォーターメロン グロウ PHA+BHA トナー',
    nameOriginal: 'Glow Recipe Watermelon Glow PHA+BHA Pore-Tight Toner',
    brand: 'Glow Recipe',
    brandCountry: 'US',
    category: 'skincare',
    tags: ['毛穴', '角質', 'PHA', 'US人気', 'デパコス'],
    description:
      '韓国系アメリカ人が創業した、K-beautyの発想をUSで再構築したブランド。スイカ果汁とPHAで毛穴の目立ちを整えるトナーです。',
    highlights: ['PHA・BHA配合のマイルドな角質ケア', 'Sephoraの人気棚常連', 'フルーティな香り'],
    popularity: 75,
    trendScore: 27,
    addedAt: '2026-03-11',
    base: { amount: 34, currency: 'USD' },
    shops: ['sephora-us', 'iherb', 'qoo10'],
  },
  {
    id: 'drunk-elephant-protini',
    name: 'Drunk Elephant プロティニ ポリペプチド クリーム',
    nameOriginal: 'Drunk Elephant Protini Polypeptide Cream',
    brand: 'Drunk Elephant',
    brandCountry: 'US',
    category: 'skincare',
    tags: ['ペプチド', 'ハリ', 'デパコス', 'US人気'],
    description:
      '9種のペプチドを配合したハリケアクリーム。日本に正規展開がないため、価格差より「そもそも手に入るか」で選ばれる商品です。',
    highlights: ['ペプチド9種配合', '日本に正規店舗がない', 'エッセンシャルオイル不使用'],
    popularity: 69,
    trendScore: 21,
    addedAt: '2026-02-22',
    base: { amount: 68, currency: 'USD' },
    shops: ['sephora-us', 'qoo10', 'rakuten'],
  },
  {
    id: 'rhode-peptide-lip-tint',
    name: 'rhode ペプチド リップ ティント',
    nameOriginal: 'rhode Peptide Lip Tint',
    brand: 'rhode',
    brandCountry: 'US',
    category: 'makeup',
    tags: ['リップ', 'ペプチド', 'US人気', 'バズり', '入手困難'],
    description:
      '発売のたびに完売するUS発のリップティント。公式は日本発送に対応しておらず、転送や代行で買う人が多いアイテムです。',
    highlights: ['ペプチド配合の保湿リップ', '再入荷のたびに完売', '公式は日本直送に非対応'],
    popularity: 73,
    trendScore: 58,
    addedAt: '2026-04-20',
    base: { amount: 18, currency: 'USD' },
    shops: ['sephora-us', 'qoo10', 'rakuten'],
  },
  {
    id: 'summer-fridays-jet-lag-mask',
    name: 'Summer Fridays ジェットラグ マスク',
    nameOriginal: 'Summer Fridays Jet Lag Mask',
    brand: 'Summer Fridays',
    brandCountry: 'US',
    category: 'skincare',
    tags: ['塗るパック', '乾燥', 'US人気', 'デパコス'],
    description:
      '洗い流さずに使える塗るタイプのマスク。旅行や乾燥する日のレスキューとして、US発の定番になりました。',
    highlights: ['洗い流し不要', 'ベタつかないバーム質感', 'クリーンビューティー'],
    popularity: 67,
    trendScore: 18,
    addedAt: '2026-03-16',
    base: { amount: 49, currency: 'USD' },
    shops: ['sephora-us', 'qoo10'],
  },
  {
    id: 'sol-de-janeiro-bum-bum-cream',
    name: 'Sol de Janeiro ブラジリアン ボム ボム クリーム',
    nameOriginal: 'Sol de Janeiro Brazilian Bum Bum Cream',
    brand: 'Sol de Janeiro',
    brandCountry: 'US',
    category: 'bodycare',
    tags: ['ボディクリーム', '香り', 'US人気', 'バズり', 'ギフト'],
    description:
      'ピスタチオとキャラメルのような甘い香りで、SNSから世界的にヒットしたボディクリーム。香りだけで選ばれる稀有な商品です。',
    highlights: ['特徴的な甘い香り', 'グアラナエキス配合', 'ギフト需要が非常に高い'],
    popularity: 79,
    trendScore: 25,
    addedAt: '2026-02-05',
    base: { amount: 48, currency: 'USD' },
    shops: ['sephora-us', 'qoo10', 'rakuten', 'amazon-jp'],
  },
  {
    id: 'olaplex-no3-hair-perfector',
    name: 'OLAPLEX No.3 ヘアパーフェクター',
    nameOriginal: 'OLAPLEX No.3 Hair Perfector',
    brand: 'OLAPLEX',
    brandCountry: 'US',
    category: 'haircare',
    tags: ['ダメージ補修', 'ブリーチ毛', 'US人気', '定番'],
    description:
      'ブリーチやカラーで傷んだ髪の結合にアプローチするトリートメント。日本国内価格と並行輸入価格の差が大きい代表例です。',
    highlights: ['サロン発のダメージ補修', 'シャンプー前に使う', '国内正規品と並行輸入で価格差が大きい'],
    popularity: 82,
    trendScore: 11,
    addedAt: '2026-01-14',
    base: { amount: 30, currency: 'USD' },
    shops: ['iherb', 'sephora-us', 'amazon-jp', 'rakuten', 'qoo10'],
  },
  {
    id: 'youth-to-the-people-cleanser',
    name: 'Youth To The People スーパーフード クレンザー',
    nameOriginal: 'Youth To The People Superfood Cleanser',
    brand: 'Youth To The People',
    brandCountry: 'US',
    category: 'skincare',
    tags: ['洗顔', 'クリーンビューティー', 'US人気', 'ヴィーガン'],
    description:
      'ケールとほうれん草のエキスを配合したジェル洗顔。クリーンビューティー文脈でUSの定番となり、日本では取扱いが限られます。',
    highlights: ['ヴィーガン・クルエルティフリー', 'メイクも落とせるジェル洗顔', 'ガラス容器でリサイクル対応'],
    popularity: 63,
    trendScore: 15,
    addedAt: '2026-03-25',
    base: { amount: 39, currency: 'USD' },
    shops: ['sephora-us', 'iherb', 'qoo10'],
  },
  {
    id: 'vital-proteins-collagen-peptides',
    name: 'Vital Proteins コラーゲン ペプチド 567g',
    nameOriginal: 'Vital Proteins Collagen Peptides',
    brand: 'Vital Proteins',
    brandCountry: 'US',
    category: 'inner-beauty',
    tags: ['コラーゲン', 'サプリ', 'US人気', '大容量'],
    description:
      '無味無臭でコーヒーにも溶けるコラーゲンパウダー。食品扱いのため、個人輸入では数量の目安（概ね2か月分以内）に注意が必要です。',
    highlights: ['無味・無臭で溶けやすい', '大容量でコスパが良い', '食品のため数量制限に注意'],
    popularity: 64,
    trendScore: 12,
    addedAt: '2026-02-19',
    base: { amount: 27, currency: 'USD' },
    shops: ['iherb', 'amazon-jp', 'rakuten'],
  },
];
